# render.yaml
services:
  - type: web
    name: telegram-trading-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BINANCE_API_KEY
        value: your_global_api_key_here
      - key: BINANCE_SECRET_KEY  
        value: your_global_secret_key_here
