'''
├─ .github/
│  └─ workflows/
│      └─ ghcr_push.yml   <- buraya koyuyorsun
'''


name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # main branch’e push olduğunda çalışacak

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}  # classic token'ı GitHub Secrets'a ekle

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/dort5bot/wobot1:latest
